dist: xenial
language: node_js
node_js:
  - "stable"
addons:
  apt:
    sources:
      - sourceline: "deb http://dl.google.com/linux/chrome/deb/ stable main"
        key_url: "https://dl-ssl.google.com/linux/linux_signing_key.pub"
    packages:
      - google-chrome-unstable
env:
  - CHROME_PATH=/usr/bin/google-chrome-unstable
script:
  - yarn checkjs
  - yarn lint
  - yarn test
